import { CollectionCard } from "@/types/CollectionCard";

export const cardListMock: CollectionCard[] = [
  {
    id: "1",
    series_short_name: "wm",
    set_short_name: "set1",
    name: { en: "test_1" },
    number: 1,
    variant: "normal",
    image: "https://example.com/test_1_image.png",
    sort_by: 1,
    total_cards_count: 0,
    rarity: "",
    illustrators: [],
    set_ids: [],
    sets: [],
    thumb: "",
  },
  {
    id: "30",
    series_short_name: "series_test1",
    set_short_name: "set1",
    name: { en: "test_1-1" },
    number: 30,
    variant: "reverse holo",
    image: "https://example.com/test_1-1_image.png",
    sort_by: 30,
    total_cards_count: 0,
    rarity: "",
    illustrators: [],
    set_ids: [],
    sets: [],
    thumb: "",
  },
  {
    id: "2",
    series_short_name: "series_test1",
    set_short_name: "set2",
    name: { en: "test_2" },
    number: 20,
    variant: "holo",
    image: "https://example.com/test_2_image.png",
    sort_by: 20,
    total_cards_count: 0,
    rarity: "",
    illustrators: [],
    set_ids: [],
    sets: [],
    thumb: "",
  },
];
